import cv2
import numpy as np
import time

# Load the image
image_path = 'images/pic.png'
image = cv2.imread(image_path)


# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Load the dictionary that was used to generate the markers.
# Here we use the 6x6 dictionary.
aruco_dict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_5X5_1000)

# Initialize the detector parameters using default values
parameters = cv2.aruco.DetectorParameters_create()

# Detect the markers in the image

time_init = time.time()
corners, ids, rejected_img_points = cv2.aruco.detectMarkers(gray, aruco_dict, parameters=parameters)
print("Time: ", time.time() - time_init)

# Draw detected markers on the image
if ids is not None:
    print("Marker detected")
    # cv2.aruco.drawDetectedMarkers(image, corners, ids)

# Display the image with detected markers

cv2.imshow('Imagen5', cv2.cvtColor(image, cv2.COLOR_BGR2RGBA))

def a():
    cv2.imshow('Imagen5', cv2.cvtColor(image, cv2.COLOR_BGR2RGBA))


    try:

        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2BGRA))
        cv2.imshow('Imagen2', cv2.cvtColor(image, cv2.COLOR_RGB2RGBA))
        cv2.imshow('Imagen3', cv2.cvtColor(image, cv2.COLOR_BGRA2BGR))
        cv2.imshow('Imagen4', cv2.cvtColor(image, cv2.COLOR_RGBA2RGB))
        
        cv2.imshow('Imagen6', cv2.cvtColor(image, cv2.COLOR_RGB2BGRA))
        cv2.imshow('Imagen7', cv2.cvtColor(image, cv2.COLOR_RGBA2BGR))
        cv2.imshow('Imagen8', cv2.cvtColor(image, cv2.COLOR_BGRA2RGB))
        cv2.imshow('Imagen9', cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
        cv2.imshow('Imagen10', cv2.cvtColor(image, cv2.COLOR_RGB2BGR))
        cv2.imshow('Imagen11', cv2.cvtColor(image, cv2.COLOR_BGRA2RGBA))
        cv2.imshow('Imagen12', cv2.cvtColor(image, cv2.COLOR_RGBA2BGRA))
        cv2.imshow('Imagen13', cv2.cvtColor(image, cv2.COLOR_BGR2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_GRAY2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_GRAY2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_GRAY2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_GRAY2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGRA2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGBA2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2BGR565))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2BGR565))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5652BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5652RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGRA2BGR565))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGBA2BGR565))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5652BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5652RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_GRAY2BGR565))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5652GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2BGR555))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2BGR555))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5552BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5552RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGRA2BGR555))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGBA2BGR555))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5552BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5552RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_GRAY2BGR555))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR5552GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2XYZ))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2XYZ))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_XYZ2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_XYZ2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2YCrCb))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2YCrCb))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YCrCb2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YCrCb2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2HSV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2HSV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2Lab))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2Lab))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2Luv))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2Luv))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2HLS))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2HLS))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_HSV2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_HSV2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_Lab2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_Lab2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_Luv2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_Luv2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_HLS2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_HLS2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2HSV_FULL))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2HSV_FULL))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2HLS_FULL))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2HLS_FULL))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_HSV2BGR_FULL))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_HSV2RGB_FULL))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_HLS2BGR_FULL))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_HLS2RGB_FULL))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_LBGR2Lab))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_LRGB2Lab))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_LBGR2Luv))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_LRGB2Luv))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_Lab2LBGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_Lab2LRGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_Luv2LBGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_Luv2LRGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2YUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2YUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_NV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_NV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_NV21))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_NV21))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420sp2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420sp2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_NV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_NV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_NV21))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_NV21))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420sp2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420sp2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_YV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_YV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_IYUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_IYUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_I420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_I420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420p2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420p2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_YV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_YV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_IYUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_IYUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_I420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_I420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420p2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420p2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_NV21))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_NV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_YV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_IYUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_I420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420sp2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV420p2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_UYVY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_UYVY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_Y422))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_Y422))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_UYNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_UYNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_UYVY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_UYVY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_Y422))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_Y422))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_UYNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_UYNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_YUY2))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_YUY2))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_YVYU))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_YVYU))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_YUYV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_YUYV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGB_YUNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGR_YUNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_YUY2))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_YUY2))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_YVYU))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_YVYU))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_YUYV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_YUYV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2RGBA_YUNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2BGRA_YUNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_UYVY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_YUY2))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_Y422))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_UYNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_YVYU))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_YUYV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_YUNV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGBA2mRGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_mRGBA2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2YUV_I420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2YUV_I420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2YUV_IYUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2YUV_IYUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGBA2YUV_I420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGRA2YUV_I420))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGBA2YUV_IYUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGRA2YUV_IYUV))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGB2YUV_YV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGR2YUV_YV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_RGBA2YUV_YV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BGRA2YUV_YV12))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBG2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGB2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRG2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGR2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRGGB2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGRBG2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBGGR2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGBRG2BGR))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRGGB2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGRBG2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBGGR2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGBRG2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBG2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGB2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRG2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGR2RGB))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBG2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGB2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRG2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGR2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRGGB2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGRBG2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBGGR2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGBRG2GRAY))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBG2BGR_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGB2BGR_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRG2BGR_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGR2BGR_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRGGB2BGR_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGRBG2BGR_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBGGR2BGR_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGBRG2BGR_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRGGB2RGB_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGRBG2RGB_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBGGR2RGB_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGBRG2RGB_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBG2RGB_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGB2RGB_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRG2RGB_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGR2RGB_VNG))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBG2BGR_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGB2BGR_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRG2BGR_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGR2BGR_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRGGB2BGR_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGRBG2BGR_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBGGR2BGR_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGBRG2BGR_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRGGB2RGB_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGRBG2RGB_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBGGR2RGB_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGBRG2RGB_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBG2RGB_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGB2RGB_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRG2RGB_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGR2RGB_EA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBG2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGB2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRG2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGR2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRGGB2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGRBG2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBGGR2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGBRG2BGRA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRGGB2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGRBG2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBGGR2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGBRG2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerBG2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGB2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerRG2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_BayerGR2RGBA))
        cv2.imshow('Imagen', cv2.cvtColor(image, cv2.COLOR_COLORCVT_MAX))
    except:
        pass
cv2.waitKey(0)
cv2.destroyAllWindows()